version: "3"

services:
  generator:
    build: generator
    environment:
      KAFKA_BROKER_URL: broker:9092
      TRANSACTIONS_TOPIC: queueing.transactions
      TRANSACTIONS_PER_SECOND: 1000
      DATASET: ${DATASET}
      LEVEL: ${LEVEL}
    volumes:
      - ../NAS:/usr/src/app/NAS/

  detector:
    build: detector
    environment:
      KAFKA_BROKER_URL: broker:9092
      TRANSACTIONS_TOPIC: queueing.transactions
      LEGIT_TOPIC: streaming.transactions.legit
      FRAUD_TOPIC: streaming.transactions.fraud
      MODEL: ${MODEL}
    volumes:
      - ../ml_kit:/usr/src/app/models/
      - ../mongodb:/usr/src/app/mongodb/

networks:
  default:
    external:
      name: kafka-network